import { exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs/promises';

const execAsync = promisify(exec);

export async function executePat(modelPath: string): Promise<{ probability: number; rawOutput: string }> {
  const outputFilePath = `${modelPath}.output.txt`;

  const command = `PAT3.Console.exe -pcsp "${modelPath}" "${outputFilePath}"`;

  try {
    await execAsync(command);
    const resultText = await fs.readFile(outputFilePath, 'utf-8'); // Read the output text file generated by PAT
    let probability = 0;
    
    const rangeMatch = resultText.match(/Probability:\s*\[([\d.]+),\s*([\d.]+)\]/i);
    const exactMatch = resultText.match(/Probability:\s*([\d.]+)/i);

    if (rangeMatch) {
      probability = parseFloat(rangeMatch[1] + parseFloat(rangeMatch[2])) / 2; // Average of the range
    } else if (exactMatch) {
      probability = parseFloat(exactMatch[1]);
    }
    return { probability, rawOutput: resultText };
    } catch (error) {
      console.error('Error running PAT model:', error);
      throw error;
    }
}

// Example usage:
// runPatModel('./models/Federer_vs_Nadal_model.pcsp')
//   .then(result => console.log('Win Probability for Player 1:', result.probability))
//   .catch(error => console.error('Error:', error));