services:
  postgres:
    container_name: cs4211_postgres
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: cs4211_admin
      POSTGRES_PASSWORD: some-secure-secret
      POSTGRES_DB: cs4211
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./data/raw/tennisabstract-v2-combined.csv:/docker-entrypoint-initdb.d/tennis.csv:ro
    restart: unless-stopped
    networks:
      - cs4211_net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cs4211_admin -d cs4211']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  cs4211_net:
    driver: bridge

volumes:
  postgres_data:
